# Generated by Django 2.2 on 2019-04-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='latidade',
            new_name='latitude',
        ),
    ]
